.Dd 2015-09-03
.Dt EUCA2OOLS 7
.Os euca2ools 3.2
.Sh NAME
.Nm euca2ools
.Nd eucalyptus command line client tools
.Sh DESCRIPTION
The
.Nm
suite is a set of command line tools that interact with
.Dq Amazon Web Services
.Pq AWS ,
Eucalyptus, and other AWS-compatible clouds using the REST-
and query-based APIs for numerous web services.
.Pp
The URL for each web service can be set with a
.Va Em SERVICE Ns No -url
region option, where
.Em SERVICE
is the name of the service, in a
.Xr euca2ools.ini 5
configuration file and then chosen with the
.Fl -region
command line option or the
.Ev AWS_DEFAULT_REGION
environment variable.  Alternatively, the URL can be
set at the command line or with an environment variable
that is specific to the service.  Environment variables
take precedence over configuration file data.
.Pp
.Nm
are designed to make it as easy as possible to work with
multiple AWS-compatible clouds from the command line using
.Xr euca2ools.ini 5
configuration files, command line options, and shortcuts.
.Ss List of Web Services
.Bl -column elasticloadbalancing 0000-00-00 AWS_CLOUDFORMATION_URL
.It Sy Name Ta Sy Version Ta Sy Environment variable Ta Sy Commands
.It autoscaling Ta 2011-01-01 Ta AWS_AUTO_SCALING_URL Ta Xr euscale-*
.It bootstrap Ta Ta EUCA_BOOTSTRAP_URL Ta
.Xr euca-bundle-image 1 ,
.Xr euca-bundle-and-upload-image 1 ,
.Xr euca-install-image 1 ,
.Xr euimage-install-pack 1
.It cloudformation Ta 2010-05-15 Ta AWS_CLOUDFORMATION_URL Ta Xr euform-*
.It ec2 Ta 2014-06-15 Ta EC2_URL Ta Xr euca-*
.It elasticloadbalancing Ta 2012-06-01 Ta AWS_ELB_URL Ta Xr eulb-*
.It iam Ta 2010-05-08 Ta AWS_IAM_URL Ta Xr euare-*
.It monitoring Ta 2010-08-01 Ta AWS_CLOUDWATCH_URL Ta Xr euwatch-*
.It s3 Ta 2006-03-01 Ta S3_URL Ta
.Xr euca-bundle-and-upload-image 1 ,
.Xr euca-download-and-unbundle 1 ,
.Xr euca-download-bundle 1 ,
.Xr euca-install-image 1 ,
.Xr euca-upload-bundle 1 ,
.Xr euimage-install-pack 1
.It sts Ta 2011-06-15 Ta TOKENS_URL Ta Xr euare-assumerole 1
.El
.Sh NOTES
The
.Dq bootstrap
service, also known as the
.Dq Empyrean
service, is specific to eucalyptus.  Commands that bundle
images can optionally use it to obtain the cloud's
signing certificate automatically, provided the cloud
runs eucalyptus 4.2 or later.
.Sh SEE ALSO
.Xr euca2ools.ini 5
