#!/usr/bin/env python

# Software License Agreement (BSD License)
#
# Copyright (c) 2009, Regents of the University of California
# All rights reserved.
#
# Redistribution and use of this software in source and binary forms, with or
# without modification, are permitted provided that the following conditions
# are met:
#
#   Redistributions of source code must retain the above
#   copyright notice, this list of conditions and the
#   following disclaimer.
#
#   Redistributions in binary form must reproduce the above
#   copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other
#   materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Author: Sunil Soman sunils@cs.ucsb.edu

import getopt, sys, os
import euca_tools
from subprocess import * 

usage_string = """
USAGE
    euca-bundle-vol -i, --image image_path -u, --user user 
	[-c, --cert cert_path] [-k, --privatekey private_key_path] 
	[-a, --all] [-e, --exclude dir1, dir2,...dirN] [-p, --prefix prefix] [-s, --size size_in_MB]
	[--[no-]inherit] [-v, --volume volume_path] [--fstab fstab_path] [--generate-fstab]
	[--kernel kernel_id] [--ramdisk ramdisk_id]
	[-B, --block-device-mapping mapping] [-d, --destination destination_path] 
	[--ec2cert ec2cert_path] [-m, --manual] [-r, --arch target_architecture] 
	[-b, --batch] 

    Where
	image_path - The path to the file system image to bundle.
	cert_path - The path to the user's PEM encoded RSA public key certificate file.
	private_key_path - The path to the user's PEM encoded RSA private key file.
	user -  The user's EC2 user ID (not the Access Key/Query Key ID).
	all - Include all directories in the volume.
	dir1, dir2,...dirN - directories to exclude
	prefix - The filename prefix for bundled files. Defaults to image name.
	size_in_MB - Size of the image file to create in MB.
	--[no-]inherit - Inherit instance metadata.
	volume_path - Path to a volume that should be bundled into the image.
	--fstab - Path to the fstab to be bundled into the image.
	--generate-fstab - Generate fstab to bundle into the image.
	kernel_id - Id of the default kernel to launch the instance with.
	ramdisk_id - Id of the default ramdisk to launch the instance with.
	mapping - Default block-device-mapping scheme.
	destination_path - The directory to create the bundle in. Defaults to '/tmp'.
	ec2cert_path - The path to the Cloud's X509 public key certificate.
	target_architecture - Target architecture ['x86_64' or 'i386'].
	-b, --batch - Run in non-interactive mode.
"""

MAX_IMAGE_SIZE = 1024 * 10

version_string = """    euca-bundle-vol version: 1.0 (BSD)"""

def usage():
    print usage_string
    sys.exit()

def version():
    print version_string
    sys.exit()

def check_root():
    chk_root = Popen(["id", "-u"], stdout=PIPE)
    id = chk_root.stdout.read().split('\n')[0]
    if id == '0':
	return
    else:
	print "Must be superuser to execute this command."
	sys.exit()

def check_image_size(size):
    if size > MAX_IMAGE_SIZE:
	print "Image Size is too large (Max = %d MB)" % (MAX_IMAGE_SIZE) 
	sys.exit()
 
def parse_excludes(excludes_string):
    excludes = []
    if excludes_string:
        excludes_string = excludes_string.replace(' ', '')
        excludes = excludes_string.split(',')
    return excludes

def main():
    euca = None
    try:
        euca = euca_tools.EucaTool('i:c:k:u:B:d:br:p:s:v:e:',
                                   ['image=', 'cert=', 'privatekey=', 'user=', 'prefix=', 'volume=',
                                    'kernel=', 'ramdisk=', 'block-device-mapping=', 'destination=', 'ec2cert=', 'arch=', 'size=', 'exclude=', 'batch'])
    except:
        usage()
  
    image_path=None
    kernel=None
    user=None
    ramdisk=None
    cert_path=os.getenv('EC2_CERT')
    private_key_path=os.getenv('EC2_PRIVATE_KEY')
    prefix=None
    size_in_MB = 10*1024
    destination_path='/disk1'
    ec2cert_path=os.getenv('EUCALYPTUS_CERT')
    target_arch='x86_64'
    mapping = None
    excludes_string = None
    batch=False
    volume_path = "/"
     
    for name, value in euca.opts:
        if name in ('-h', '--help'):
            usage()
        elif name in ('-i', '--image'):
            image_path = value
        elif name in ('-c', '--cert'):
            cert_path = value
        elif name in ('-k', '--privatekey'):
            private_key_path = value
        elif name in ('-u', '--user'):
            user = value
        elif name in ('--kernel'):
            kernel = value
        elif name in ('--ramdisk'):
            ramdisk = value
        elif name in ('-p', '--prefix'):
            prefix = value
        elif name in ('-s', '--size'):
            size_in_MB = int(value)
        elif name in ('-v', '--volume'):
            volume_path = value
        elif name in ('-e', '--exclude'):
            excludes_string = value
        elif name in ('-d', '--destination'):
            destination_path = value
        elif name in ('--ec2cert'):
            ec2cert_path = value
        elif name in ('-r', '--arch'):
            target_arch = value
	    print target_arch
	    if target_arch != 'i386' and target_arch != 'x86_64':
		print 'target architecture must be i386 or x86_64'
		usage()
	elif name in ('-B', '--block-device-mapping'):
	    mapping = value
	elif name in ('--batch'):
	    batch = True

    if image_path and cert_path and private_key_path and user and ec2cert_path:
	check_root()
	check_image_size(size_in_MB)
	excludes = parse_excludes(excludes_string)
	euca_tools.add_excludes(volume_path, excludes)
	print volume_path, excludes
	if not prefix:
            prefix = euca_tools.get_absolute_filename(image_path)
	image_path = euca_tools.make_image(size_in_MB, excludes, prefix, destination_path)        
        euca_tools.copy_volume(image_path, volume_path, excludes)
	image_size, sha_image_digest = euca_tools.check_image(image_path, destination_path)
	if not prefix:
            prefix = euca_tools.get_absolute_filename(image_path)
	tar_file = euca_tools.tar_image(prefix, image_path, destination_path)
	zip_file = euca_tools.zip_image(tar_file)
	os.remove(tar_file)
	encrypted_file, key, iv, bundled_size = euca_tools.encrypt_image(zip_file)
	os.remove(zip_file)
	parts, parts_digest = euca_tools.split_image(encrypted_file)
	euca_tools.generate_manifest(destination_path, prefix, parts, parts_digest, image_path, key, iv, cert_path, ec2cert_path, private_key_path, target_arch, image_size, bundled_size, sha_image_digest, user, kernel, ramdisk, mapping)
        os.remove(encrypted_file)
    else:
	print 'image, cert, privatekey, user and ec2cert_path MUST be specified.'
	usage()
if __name__ == "__main__":
    main()
       

